#!/bin/bash -
DIR="$(dirname "$0")"
tar xf "$DIR/projet_java/Code/openjfx-21.0.2_osx-aarch64_bin-sdk.tar.xz" -C "$DIR/projet_java/Code/"
tar xf "$DIR/projet_java/Code/openjfx-21.0.2_osx-x64_bin-sdk.tar.xz" -C "$DIR/projet_java/Code/"
java --module-path "$DIR/projet_java/Code/openjfx-21.0.2_osx-x64_bin-sdk/javafx-sdk-21.0.2/lib" --add-modules javafx.controls,javafx.fxml,javafx.media,javafx.web,javafx.swing,javafx.graphics,javafx.base -jar MyApplication.jar || java --module-path "$DIR/projet_java/Code/openjfx-21.0.2_osx-aarch64_bin-sdk/javafx-sdk-21.0.2/lib" --add-modules javafx.controls,javafx.fxml,javafx.media,javafx.web,javafx.swing,javafx.graphics,javafx.base -jar MyApplication.jar